### ISSUE TITLE
some question about paper on "A SINGLE-CHANNEL NOISE REDUCTION MVDR FILTER"

### ISSUE THREAD

**Issue by ltcxjtu** [XianruiWang/HenrySignal#1]
Hi Xianrui:
    I had some interest in your advisor's paper about MVDR used in single channel using muti-frame;There are some questions:
    1.I'm not understand the inter correlation in each freq bin,as far as I know, the AR model for speech is used in time domain like LPC  to estimation the coefficient, some inter correlation maybe have little in high freq. So the length of AR model might not be same.
    2.The " desired signal vector " in each freq-bin like the para in AR model in time domain,compared to multi-channel,like "doa vector".I think it's not invariable (doa vector can assume to be the same ) for a certain time.
    3.last and the most important,can you share me some demo code about the algorithm.

**Comment by XianruiWang** [comment]
Thank you for providing the information. Please find below a refined version:

Attached, you will find details on the time-domain Single-Channel Multiframe Distortionless Minimum Variance Response (MF-MVDR), which is implemented in the time domain. Additionally, it's worth noting that time-domain linear prediction can also be implemented in the Short-Time Fourier Transform (STFT) domain, with techniques such as Weighted Prediction Error (WPE). If you have any further questions or if there's anything specific you'd like to discuss regarding these methods, please feel free to let me know!
